### ISSUE TITLE
Keep OOP and abstractions

### ISSUE THREAD

**Issue by klcity** [klcity/cs5351-grp3#5]
OOP is adopted in the project, global functions should be defined for 100% general cases e.g. creating Gaussian Random numbers.

The following function has dedicated purpose and should be encapsulated with abstraction.
abstract UML_ObjectParser
UML_ClassParser extends UML_ObjectParser
UML_InterfaceParser extends UML_ObjectParser

https://github.com/klcity/cs5351-grp3/blob/efbfcf784194938ff1530060aa8071d078b25f49/src/js/parser.js#L372-L386

**Comment by hmwong237** [comment]
UML_ObjectParser class created
